# Generated by Django 4.0.5 on 2022-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
