# Generated by Django 4.0.5 on 2022-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_users_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='key',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
