# Generated by Django 4.0.5 on 2022-06-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_sections_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.languages')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.sections')),
            ],
        ),
    ]
