# Generated by Django 4.0.5 on 2022-06-15 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_eng', models.TextField()),
                ('text_ar', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='text_ar',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='lang',
        ),
        migrations.AddField(
            model_name='messages',
            name='text_eng',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lang',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('ar', 'Arabic')], max_length=55, null=True),
        ),
        migrations.DeleteModel(
            name='Buttons',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.AddField(
            model_name='button_message',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.sections'),
        ),
    ]
