# Generated by Django 4.0.5 on 2022-06-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_button_message_rename_message_messages_text_ar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Button_message',
        ),
    ]
