# Generated by Django 4.0.5 on 2022-06-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_users_instagram_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255)),
                ('name_ar', models.TextField(max_length=255)),
            ],
        ),
    ]
