# Generated by Django 4.0.5 on 2022-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255),
        ),
    ]
