# Generated by Django 4.0.5 on 2022-06-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_servicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.CharField(blank=True, max_length=125, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('lefquantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('done', 'Finished')], max_length=125)),
                ('servicecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.servicecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.users')),
            ],
        ),
    ]
