# Generated by Django 4.0.5 on 2022-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_services_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='coin',
            field=models.IntegerField(default=0),
        ),
    ]
